name: minhafesta
description: Organizador de festas
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  floor: ^1.3.0
  sqflite: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.0
  floor_generator: ^1.3.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true